USE garagevparrot;
CREATE TABLE testimony_Status (
    id TINYINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ValidateStatus VARCHAR(255) NOT NULL,
    isValidated BOOLEAN NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);