
    CREATE USER IF NOT EXISTS 'administrator'@'%' IDENTIFIED BY '@dmiN123' ;
    GRANT ALL PRIVILEGES ON *.* TO 'administrator'@'%' IDENTIFIED BY '@dmiN123' WITH GRANT OPTION;
    CREATE USER IF NOT EXISTS 'employee'@'%' IDENTIFIED BY 'Empl@Yee123';
    GRANT SELECT, INSERT, UPDATE, CREATE, DELETE ON garage.* TO 'employee'@'%' IDENTIFIED BY 'Empl@Yee123';


