
CREATE USER IF NOT EXISTS 'administrator'@'%' IDENTIFIED BY '@dmiN123' ;
GRANT ALL PRIVILEGES ON *.* TO 'administrator'@'%' IDENTIFIED BY '@dmiN123' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'garage'@'%' IDENTIFIED BY 'G@r@ge123';
GRANT SELECT, INSERT, UPDATE, CREATE, DELETE ON garage.* TO 'garage'@'%' IDENTIFIED BY 'G@r@ge123';
